Task 1
pornoiya/Robots pull request #1
Opened 2020-04-22 09:25 UTC by pornoiya

2020-04-25 18:13 UTC, shaykemelov reviewed
при нажатии на крестик окно подтверждения тоже должно появляться.<br>
кнопка выход в меню ооочень  большая получилась, так было задумано?

2020-04-25 18:13 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private void exitManager(JMenuItem menuItem)
может просто `exit`?<br>
`menuItem` не используется, можно убрать параметр

2020-04-29 14:36 UTC, shaykemelov requested changes
tofix

2020-05-06 16:21 UTC, pornoiya commented
@shaykemelov done

2020-05-16 10:22 UTC, shaykemelov approved these changes
lgtm

2020-05-16 10:22 UTC, merged