task2 refactored
pornoiya/Robots pull request #5
Opened 2020-05-18 09:09 UTC by pornoiya

сделала все по инструкции 1

2020-05-18 09:09 UTC, pornoiya commented
@shaykemelov

2020-05-23 19:28 UTC, shaykemelov requested changes
механизм сохранения/восстановления состояния не работает, если закрывать приложение через элемент меню, который был реализован в первом задании

2020-05-23 19:28 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +        }
`MainApplicationFrame` - это фрейм. Он не должен что-либо знать о том, что существует какой-то файлик, который как-то сохраняется на файловой системе. эту логику следует вынести за пределы класса.

2020-06-01 11:10 UTC, pornoiya commented
@all
сохранение окошек через "управление -> выход"
изолирование логики работы с json

2020-06-02 22:50 UTC, shaykemelov requested changes
tofix

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +                    WindowStateControl.saveState(states);
В методе `createExitActionListener()` и `exit()` дублирующийся код и как показал текущий опыт - с ним появляются проблемы, а именно необходимо вносить одни и те же изменения в разные места. нужно вынести этот код в общее место

2020-06-02 22:50 UTC, shaykemelov commented on windowStates.json
> +{"Игровое поле":{"isMaximized":false,"x":332,"y":7,"isMinimized":true},"Протокол работы":{"isMaximized":false,"x":121,"y":2,"isMinimized":false}}
думаю этот файл стоит исключить из коммита

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/WindowStateControl.java
> +}
хоть в `Java` и разрешено так объявлять классы, все же это считается плохим тоном. действительно ли нужен этот класс? если да, то лучше в отдельный файл вынести

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +                WindowStateControl.saveState(states);
дальше ведь вызывается `exit()` и там выполняется точно такой же код

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +                WindowStateControl.saveState(states);
в текущей реализации состояние будет сохраняться на диск каждый раз, когда пользователь будет нажимать на кнопку выход, но он ведь может и передумать

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    public ArrayList<JInternalFrame> windows = new ArrayList<>();
При объявлении лучше использовать интерфейс, чтобы весь остальной код не был завязан на реализации. 
Поле класса нужно делать `private` и желательно `final`

`private final List<JInternalFrame> windows = new ArrayList<>();`

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
>          return new WindowAdapter() {
этот анонимный класс может быть вложенным статическим

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    protected WindowAdapter createExitActionListener(ArrayList<JInternalFrame> frames) {
метод используется только внутри класса т.е. должен быть `private` как и другие такие методы

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    protected WindowAdapter createExitActionListener(ArrayList<JInternalFrame> frames) {
Снова завязка на реализации списка, замени `ArrayList` на `List`

2020-06-02 22:50 UTC, shaykemelov commented on robots/src/gui/WindowStateControl.java
> +    static HashMap<String, HashMap> getState(ArrayList<JInternalFrame> frames) {
1. использование сырых контейнеров без дженериков ведет к дальнейшим ошибкам. Нужно исправить это везде в этом классе
2. и снова завязка на реализации HashMap

`HashMap` -> `Map<T1, T2>`

2020-06-07 14:06 UTC, pornoiya commented on robots/src/gui/MainApplicationFrame.java
> +                WindowStateControl.saveState(states);
но, файл не обновляется если просто нажать на выход, не нажимая "да"

2020-06-08 10:03 UTC, pornoiya commented
@shaykemelov

2020-06-13 12:43 UTC, shaykemelov requested changes
приложение не запускается, если файл с сохраненным состоянием не найден

tofix

2020-06-13 12:44 UTC, shaykemelov commented
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gui.State.toState(State.java:29)
	at gui.WindowStateControl.lambda$readState$1(WindowStateControl.java:53)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at gui.WindowStateControl.readState(WindowStateControl.java:52)
	at gui.WindowStateControl.initStateFile(WindowStateControl.java:78)
	at gui.MainApplicationFrame.<init>(MainApplicationFrame.java:37)
	at gui.RobotsProgram.lambda$main$0(RobotsProgram.java:20)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

2020-06-16 11:39 UTC, pornoiya commented
@shaykemelov bug fixed

2020-06-19 18:12 UTC, merged